#ifndef AVA_BLUETOOTH_H
#define AVA_BLUETOOTH_H

#include <Arduino.h>
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>
#include <BLEAdvertising.h>

#include <esp_mac.h>
#include <esp_bt_device.h>

#include "Ava_Eyes.h"
#include "Ava_Config.h"
#include "Ava_TicTacToe.h"
#include "AVA_GAMES.h"

namespace AvaBluetooth {

static constexpr const char* SERVICE_UUID = "7b7a0001-6a76-4156-9a76-415641000001";
static constexpr const char* COMMAND_UUID = "7b7a0002-6a76-4156-9a76-415641000001";
static constexpr const char* EVENT_UUID = "7b7a0003-6a76-4156-9a76-415641000001";
static constexpr const char* STATE_UUID = "7b7a0004-6a76-4156-9a76-415641000001";
static constexpr const char* DATA_UUID = "7b7a0005-6a76-4156-9a76-415641000001";

inline BLEServer*& server(){ static BLEServer* value=nullptr; return value; }
inline BLEService*& service(){ static BLEService* value=nullptr; return value; }
inline BLECharacteristic*& commandCharacteristic(){ static BLECharacteristic* value=nullptr; return value; }
inline BLECharacteristic*& eventCharacteristic(){ static BLECharacteristic* value=nullptr; return value; }
inline BLECharacteristic*& stateCharacteristic(){ static BLECharacteristic* value=nullptr; return value; }
inline BLECharacteristic*& dataCharacteristic(){ static BLECharacteristic* value=nullptr; return value; }
inline String& receivedData(){ static String value=""; return value; }
inline bool& dataPending(){ static bool value=false; return value; }
inline String& receivedCommand(){ static String value=""; return value; }
inline bool& commandPending(){ static bool value=false; return value; }
inline bool& connected(){ static bool value=false; return value; }
inline bool& connectionEventPending(){ static bool value=false; return value; }
inline void sendEvent(const String& message); inline void sendState(const String& state); inline void sendData(const String& data); inline void executeCommand(const String& command); inline void processData(const String& data); inline void processGameAnswer(const String& data);
inline bool hasData(){ return dataPending(); }
inline String readData(){ if(!dataPending()) return ""; String data=receivedData(); receivedData()=""; dataPending()=false; return data; }
inline bool hasCommand(){ return commandPending(); }
inline String readCommand(){ if(!commandPending()) return ""; String command=receivedCommand(); receivedCommand()=""; commandPending()=false; return command; }
inline void sendGameQuestion(){ String message="GAME_QUESTION|"; message+=String(AvaGames::getCurrentRound()); if(AvaGames::getCurrentGame()==AvaGames::GAME_LOGIC_BATTLE){ message+="|"; message+=AvaGames::getLogicQuestionText(); for(int i=0;i<4;i++){ message+="|"; message+=String(AvaGames::getOption(i)); } sendData(message); return; } message+="|"; message+=String(AvaGames::getQuestionA()); message+="|"; message+=String(AvaGames::getQuestionB()); message+="|"; message+=String(AvaGames::getQuestionOperator()); for(int i=0;i<4;i++){ message+="|"; message+=String(AvaGames::getOption(i)); } sendData(message); }
inline void sendGameScore(){ String message="GAME_SCORE|"; message+=String(AvaGames::getAliScore()); message+="|"; message+=String(AvaGames::getAvaScore()); sendData(message); }
inline void sendGameResult(){ String message="GAME_RESULT|"; message+=String(AvaGames::getCurrentRound()); message+="|"; message+=String(AvaGames::getAliAnswer()); message+="|"; message+=String(AvaGames::getAvaAnswer()); message+="|"; message+=AvaGames::isAliCorrect()?"1":"0"; message+="|"; message+=AvaGames::isAvaCorrect()?"1":"0"; sendData(message); }
inline void sendAvaGameAnswer(){ String message="GAME_ANSWER|AVA|"; message+=String(AvaGames::getAvaAnswer()); sendData(message); }
inline void sendGameFinished(){ String message="GAME_FINISHED|"; message+=AvaGames::getWinner(); message+="|"; message+=String(AvaGames::getAliScore()); message+="|"; message+=String(AvaGames::getAvaScore()); sendData(message); }
inline void processGameAnswer(const String& data){ const String prefix="GAME_ANSWER|"; if(!data.startsWith(prefix)) return; String payload=data.substring(prefix.length()); int separator=payload.indexOf('|'); if(separator<0){ sendData("GAME_ANSWER_FAILED"); return; } String player=payload.substring(0,separator); String answerText=payload.substring(separator+1); player.trim(); answerText.trim(); player.toUpperCase(); if(answerText.length()==0){ sendData("GAME_ANSWER_FAILED"); return; } int answer=answerText.toInt(); if(player=="ALI"){ if(!AvaGames::isRunning()){ sendData("GAME_ANSWER_FAILED|GAME_NOT_RUNNING"); return; } if(AvaGames::hasAliAnswered()){ sendData("GAME_ANSWER_FAILED|ALREADY_ANSWERED"); return; } bool correct=AvaGames::submitAnswer(AvaGames::PLAYER_ALI,answer); String response="GAME_ANSWER_ACCEPTED|ALI|"; response+=correct?"1":"0"; sendData(response); int generatedAvaAnswer=AvaGames::generateAvaAnswer(); AvaGames::submitAnswer(AvaGames::PLAYER_AVA,generatedAvaAnswer); } else if(player=="AVA"){ sendData("GAME_ANSWER_FAILED|AVA_INTERNAL_ONLY"); return; } else { sendData("GAME_ANSWER_FAILED|UNKNOWN_PLAYER"); return; } if(!AvaGames::bothPlayersAnswered()) return; AvaGames::applyRoundScore(); sendAvaGameAnswer(); sendGameResult(); sendGameScore(); if(AvaGames::nextRound()) sendGameQuestion(); else sendGameFinished(); }
inline String ticTacToeWinnerText(){ char winner=AvaTicTacToe::getWinner(); if(winner==AvaTicTacToe::ALI) return "ALI"; if(winner==AvaTicTacToe::AVA) return "AVA"; return "DRAW"; }
inline void sendTicTacToeState(){ String message="TTT_STATE|"+AvaTicTacToe::getBoardString()+"|"+String(AvaTicTacToe::getTurn()); sendData(message); }
inline void sendTicTacToeScore(){ String message="TTT_SCORE|"+String(AvaTicTacToe::getAliScore())+"|"+String(AvaTicTacToe::getAvaScore()); sendData(message); }
inline void sendTicTacToeFinished(){ String winner=ticTacToeWinnerText(); sendData("TTT_RESULT|"+winner); sendTicTacToeScore(); sendData("TTT_FINISHED|"+winner); }
inline void startTicTacToe(){ AvaTicTacToe::resetGame(); setGaze(GAZE_DOWN); sendEvent("GAME_STARTED"); sendTicTacToeScore(); sendTicTacToeState(); Serial.println("[TTT BLE] TIC TAC TOE STARTED."); Serial.println("[TTT BLE] ALI = X | AVA = O"); }
inline void processTicTacToeMove(const String& data){ const String prefix="TTT_MOVE|"; if(!data.startsWith(prefix)) return; String payload=data.substring(prefix.length()); int separator=payload.indexOf('|'); if(separator<0){ sendData("TTT_MOVE_REJECTED|INVALID_FORMAT"); return; } String player=payload.substring(0,separator); String cellText=payload.substring(separator+1); player.trim(); cellText.trim(); player.toUpperCase(); if(player!="ALI"){ sendData("TTT_MOVE_REJECTED|ALI_ONLY"); return; } int cell=cellText.toInt(); if(cell<0||cell>8){ sendData("TTT_MOVE_REJECTED|INVALID_CELL"); return; } if(!AvaTicTacToe::isRunning()){ sendData("TTT_MOVE_REJECTED|GAME_NOT_RUNNING"); return; } if(AvaTicTacToe::getTurn()!=AvaTicTacToe::ALI){ sendData("TTT_MOVE_REJECTED|NOT_YOUR_TURN"); return; } if(!AvaTicTacToe::aliMove(cell)){ sendData("TTT_MOVE_REJECTED|INVALID_MOVE"); return; } sendData("TTT_MOVE_ACCEPTED|ALI|"+String(cell)); sendTicTacToeState(); if(AvaTicTacToe::isFinished()){ sendTicTacToeFinished(); return; } int avaCell=AvaTicTacToe::makeAvaMove(); if(avaCell<0){ sendData("TTT_MOVE_REJECTED|AVA_MOVE_FAILED"); return; } sendData("TTT_MOVE|AVA|"+String(avaCell)); sendTicTacToeState(); if(AvaTicTacToe::isFinished()) sendTicTacToeFinished(); }
inline void processData(const String& data){ String value=data; value.trim(); if(value.length()==0) return; if(value.startsWith("GAME_ANSWER|")){ processGameAnswer(value); return; } if(value.startsWith("TTT_MOVE|")){ processTicTacToeMove(value); return; } if(value=="TTT_REMATCH"){ setGaze(GAZE_DOWN); if(AvaTicTacToe::rematch()){ sendEvent("GAME_STARTED"); sendTicTacToeScore(); sendTicTacToeState(); sendData("TTT_REMATCHED"); } return; } receivedData()=value; dataPending()=true; }
inline void executeCommand(const String& command){ String cmd=command; cmd.trim(); cmd.toUpperCase(); Serial.print("[BLE] Executing: "); Serial.println(cmd); if(cmd=="HELLO_AVA"){ renderEyes(EYES_LISTENING); sendEvent("HELLO_AVA_ACK"); return; } if(cmd=="EYES_CALM"){ renderEyes(EYES_CALM); sendEvent("EYES_CALM"); return; } if(cmd=="EYES_HAPPY"){ renderEyes(EYES_HAPPY); sendEvent("EYES_HAPPY"); return; } if(cmd=="EYES_SAD"){ renderEyes(EYES_SAD); sendEvent("EYES_SAD"); return; } if(cmd=="EYES_SLEEPY"){ renderEyes(EYES_SLEEPY); sendEvent("EYES_SLEEPY"); return; } if(cmd=="EYES_THINKING"){ renderEyes(EYES_THINKING); sendEvent("EYES_THINKING"); return; } if(cmd=="EYES_LISTENING"){ renderEyes(EYES_LISTENING); sendEvent("EYES_LISTENING"); return; } if(cmd=="EYES_SURPRISED"){ renderEyes(EYES_SURPRISED); sendEvent("EYES_SURPRISED"); return; } if(cmd=="BLINK"){ EyeState previousState=avaCurrentEyeState; renderEyes(EYES_BLINK); delay(120); renderEyes(previousState); sendEvent("BLINK"); return; } if(cmd=="TIME_REQUEST"){ sendEvent("TIME_REQUEST"); return; } if(cmd=="DEBUG OLED"){ avaApplyEmotion(AVA_EMOTION_NORMAL); sendEvent("DEBUG_OLED"); return; } if(cmd=="GAME_LOAD|TIC_TAC_TOE"){ startTicTacToe(); return; } if(cmd=="TTT_REMATCH"){ setGaze(GAZE_DOWN); if(AvaTicTacToe::rematch()){ sendEvent("GAME_STARTED"); sendTicTacToeScore(); sendTicTacToeState(); sendData("TTT_REMATCHED"); } return; } if(cmd.startsWith("GAME_LOAD|")){ String gameId=cmd.substring(String("GAME_LOAD|").length()); gameId.trim(); if(AvaGames::loadGame(gameId)) sendEvent("GAME_LOADED|"+gameId); else sendEvent("GAME_LOAD_FAILED|"+gameId); return; } if(cmd=="GAME_START"){ if(AvaTicTacToe::isRunning()){ startTicTacToe(); return; } if(AvaGames::startGame()){ sendEvent("GAME_STARTED"); sendGameQuestion(); } else sendEvent("GAME_START_FAILED"); return; } if(cmd=="GAME_END"){ if(AvaTicTacToe::isRunning()||AvaTicTacToe::isFinished()){ AvaTicTacToe::resetGame(); sendEvent("GAME_ENDED"); return; } AvaGames::endGame(); sendEvent("GAME_ENDED"); sendGameFinished(); return; } if(cmd=="GAME_RESET"){ AvaGames::reset(); sendEvent("GAME_RESET"); return; } sendEvent("UNKNOWN_COMMAND"); }
class ServerCallbacks:public BLEServerCallbacks{public:void onConnect(BLEServer* pServer)override{connected()=true;connectionEventPending()=true;Serial.println("[BLE] Phone connected.");}void onDisconnect(BLEServer* pServer)override{connected()=false;connectionEventPending()=false;Serial.println("[BLE] Phone disconnected.");BLEDevice::startAdvertising();Serial.println("[BLE] Advertising restarted.");}};
class CommandCallbacks:public BLECharacteristicCallbacks{public:void onWrite(BLECharacteristic* characteristic)override{if(characteristic==nullptr)return;std::string value=characteristic->getValue();if(value.empty())return;String command=String(value.c_str());command.trim();if(command.length()==0)return;Serial.print("[BLE RX] COMMAND: ");Serial.println(command);if(!commandPending()){receivedCommand()=command;commandPending()=true;Serial.println("[BLE] COMMAND queued for main loop.");}else Serial.println("[BLE] WARNING: COMMAND buffer busy.");}};
class DataCallbacks:public BLECharacteristicCallbacks{public:void onWrite(BLECharacteristic* characteristic)override{if(characteristic==nullptr)return;std::string value=characteristic->getValue();if(value.empty())return;String data=String(value.c_str());data.trim();if(data.length()==0)return;Serial.print("[BLE RX] DATA: ");Serial.println(data);if(!dataPending()){receivedData()=data;dataPending()=true;Serial.println("[BLE] DATA queued for main loop.");}else Serial.println("[BLE] WARNING: DATA buffer busy.");}};
inline bool begin(){ BLEDevice::init("AVA"); server()=BLEDevice::createServer(); if(server()==nullptr)return false; server()->setCallbacks(new ServerCallbacks()); service()=server()->createService(SERVICE_UUID); if(service()==nullptr)return false; commandCharacteristic()=service()->createCharacteristic(COMMAND_UUID,BLECharacteristic::PROPERTY_WRITE|BLECharacteristic::PROPERTY_WRITE_NR); if(commandCharacteristic()==nullptr)return false; commandCharacteristic()->setCallbacks(new CommandCallbacks()); eventCharacteristic()=service()->createCharacteristic(EVENT_UUID,BLECharacteristic::PROPERTY_READ|BLECharacteristic::PROPERTY_NOTIFY); if(eventCharacteristic()==nullptr)return false; eventCharacteristic()->addDescriptor(new BLE2902()); stateCharacteristic()=service()->createCharacteristic(STATE_UUID,BLECharacteristic::PROPERTY_READ|BLECharacteristic::PROPERTY_NOTIFY); if(stateCharacteristic()==nullptr)return false; stateCharacteristic()->addDescriptor(new BLE2902()); dataCharacteristic()=service()->createCharacteristic(DATA_UUID,BLECharacteristic::PROPERTY_READ|BLECharacteristic::PROPERTY_WRITE|BLECharacteristic::PROPERTY_WRITE_NR|BLECharacteristic::PROPERTY_NOTIFY); if(dataCharacteristic()==nullptr)return false; dataCharacteristic()->addDescriptor(new BLE2902()); dataCharacteristic()->setCallbacks(new DataCallbacks()); service()->start(); BLEAdvertising* advertising=BLEDevice::getAdvertising(); if(advertising==nullptr)return false; advertising->addServiceUUID(SERVICE_UUID); advertising->setScanResponse(true); advertising->setMinPreferred(0x06); advertising->setMinPreferred(0x12); BLEDevice::startAdvertising(); return true; }
inline void update(){ if(connectionEventPending()){ if(!connected()){connectionEventPending()=false;return;} connectionEventPending()=false; sendEvent("AVA_CONNECTED"); } if(commandPending()){ String command=readCommand(); if(command.length()>0){ Serial.println("[BLE] Processing queued COMMAND from main loop..."); executeCommand(command); } } if(dataPending()){ String data=readData(); if(data.length()>0){ Serial.println("[BLE] Processing queued DATA from main loop..."); processData(data); } } }
inline bool isConnected(){return connected();}
inline void sendEvent(const String& message){BLECharacteristic* characteristic=eventCharacteristic();if(characteristic==nullptr)return;characteristic->setValue(message.c_str());if(connected())characteristic->notify();Serial.print("[BLE TX] EVENT: ");Serial.println(message);}
inline void sendState(const String& state){BLECharacteristic* characteristic=stateCharacteristic();if(characteristic==nullptr)return;characteristic->setValue(state.c_str());if(connected())characteristic->notify();Serial.print("[BLE TX] STATE: ");Serial.println(state);}
inline void sendData(const String& data){BLECharacteristic* characteristic=dataCharacteristic();if(characteristic==nullptr)return;characteristic->setValue(data.c_str());if(connected())characteristic->notify();Serial.print("[BLE TX] DATA: ");Serial.println(data);}
}
#endif